"""
Alchemy Prototypes

All 66 alchemy substance recipes sourced from the EldritchMUSH crafting spreadsheet.
Sections: Apotheca, Poison, Drug — Levels 1, 2, 3

craft_source = "apothecary"  — consumed by alchemy crafting system.
substance_type: "apotheca", "poison", or "drug".
fee_silver: silver dragons paid to Apothecary guild per batch.
qty_produced: number of doses produced per crafting session.
reagent_1..5: ingredient names, quantities, and rarities.
Reagent 5 is a bonus ingredient (name only in source spreadsheet).
value_copper/silver/gold: market purchase price.
"""


# ==== Level 1 Apotheca ====

ANAMNESIS_DECOCTION = {
    "typeclass": "typeclasses.objects.ConsumableObject",
    "key": "Anamnesis Decoction",
    "aliases": ["anamnesis decoction"],
    "craft_source": "apothecary",
    "substance_type": "apotheca",
    "level": 1,
    "effect": "Required in the Apotheca's Anamnesis ability",
    "fee_silver": 5,
    "qty_produced": 5,
    "reagent_1": "Distilled Spirits",
    "reagent_1_qty": 2,
    "reagent_1_rarity": "Common",
    "reagent_2": "Sayge",
    "reagent_2_qty": 1,
    "reagent_2_rarity": "Uncommon",
    "reagent_3": "Widow's Petal",
    "reagent_3_qty": 1,
    "reagent_3_rarity": "Uncommon",
    "reagent_4": "Harrowdust",
    "reagent_4_qty": 1,
    "reagent_4_rarity": "Common",
    "reagent_5": "Sayge",
    "value_copper": 58,
    "value_silver": 5,
    "value_gold": 0,
}

BLADE_OIL = {
    "typeclass": "typeclasses.objects.ConsumableObject",
    "key": "Blade Oil",
    "aliases": ["blade oil"],
    "craft_source": "apothecary",
    "substance_type": "apotheca",
    "level": 1,
    "effect": "Applied to a weapon to convert any one Active Martial call into a Cleave and allows the skill to be used with 1-Handed weapons. This potion’s effects are canceled the next time the player uses the Cleave effect or the event ends. A weapon can only have one oil/salve on it at a time.",
    "fee_silver": 1,
    "qty_produced": 1,
    "reagent_1": "Distilled Spirits",
    "reagent_1_qty": 1,
    "reagent_1_rarity": "Common",
    "reagent_2": "Dragon's Eye",
    "reagent_2_qty": 1,
    "reagent_2_rarity": "Common",
    "reagent_3": "Dragon's Eye",
    "reagent_3_qty": 1,
    "reagent_3_rarity": "Common",
    "reagent_4": "Dragon's Eye",
    "reagent_4_qty": 2,
    "reagent_4_rarity": "Common",
    "reagent_5": "Verbaena",
    "value_copper": 53,
    "value_silver": 5,
    "value_gold": 0,
}

BLADE_SALVE = {
    "typeclass": "typeclasses.objects.ConsumableObject",
    "key": "Blade Salve",
    "aliases": ["blade salve"],
    "craft_source": "apothecary",
    "substance_type": "apotheca",
    "level": 1,
    "effect": "Applied to a weapon to allow it to absorb 1 additional Sunder. This effect lasts until the weapon is Sundered next or the event ends. A weapon can only have one oil/salve on it at a time.",
    "fee_silver": 3,
    "qty_produced": 3,
    "reagent_1": "Distilled Spirits",
    "reagent_1_qty": 2,
    "reagent_1_rarity": "Common",
    "reagent_2": "Sayge",
    "reagent_2_qty": 1,
    "reagent_2_rarity": "Common",
    "reagent_3": "Willow Root",
    "reagent_3_qty": 0,
    "reagent_3_rarity": "Common",
    "reagent_4": "Verbaena",
    "reagent_4_qty": 1,
    "reagent_4_rarity": "Common",
    "reagent_5": "Verbaena",
    "value_copper": 44,
    "value_silver": 4,
    "value_gold": 0,
}

BULLS_DECOCTION = {
    "typeclass": "typeclasses.objects.ConsumableObject",
    "key": "Bull's Decoction",
    "aliases": ["bull's decoction"],
    "craft_source": "apothecary",
    "substance_type": "apotheca",
    "level": 1,
    "effect": "Convert one Active Martial call into a Sunder and allows the skill to be used with any 1-Handed weapon. This potion’s effects are canceled the next time the player uses a Sunder effect or the event ends. Does not stack with itself or other consumables that grant Sunder.",
    "fee_silver": 7,
    "qty_produced": 7,
    "reagent_1": "Distilled Spirits",
    "reagent_1_qty": 1,
    "reagent_1_rarity": "Common",
    "reagent_2": "Dragon's Eye",
    "reagent_2_qty": 1,
    "reagent_2_rarity": "Common",
    "reagent_3": "Dragon's Eye",
    "reagent_3_qty": 1,
    "reagent_3_rarity": "Common",
    "reagent_4": "Gold Lotus",
    "reagent_4_qty": 1,
    "reagent_4_rarity": "Common",
    "reagent_5": "Phosphorous",
    "value_copper": 48,
    "value_silver": 4,
    "value_gold": 0,
}

CATS_EYES = {
    "typeclass": "typeclasses.objects.ConsumableObject",
    "key": "Cat's Eyes",
    "aliases": ["cat's eyes"],
    "craft_source": "apothecary",
    "substance_type": "apotheca",
    "level": 1,
    "effect": "Must be used in the dark. Cat’s Eyes allows user to see in the “darkness” until they are exposed to daylight. Some encounters will feature a simulated darkness which causes blindness.",
    "fee_silver": 5,
    "qty_produced": 5,
    "reagent_1": "Distilled Spirits",
    "reagent_1_qty": 1,
    "reagent_1_rarity": "Common",
    "reagent_2": "Gold Lotus",
    "reagent_2_qty": 1,
    "reagent_2_rarity": "Common",
    "reagent_3": "Gold Lotus",
    "reagent_3_qty": 2,
    "reagent_3_rarity": "Common",
    "reagent_4": "Orgonnian Grapes",
    "reagent_4_qty": 1,
    "reagent_4_rarity": "Common",
    "reagent_5": "Willow Root",
    "value_copper": 56,
    "value_silver": 5,
    "value_gold": 0,
}

CATS_PAW = {
    "typeclass": "typeclasses.objects.ConsumableObject",
    "key": "Cat's Paw",
    "aliases": ["cat's paw"],
    "craft_source": "apothecary",
    "substance_type": "apotheca",
    "level": 1,
    "effect": "Gain 1 temporary level of the Disarm Device skill (Max 3) until a different potion is consumed or 30 minutes have passed. Does not stack with itself or other consumables that grant Disarm Device.",
    "fee_silver": 3,
    "qty_produced": 3,
    "reagent_1": "Distilled Spirits",
    "reagent_1_qty": 2,
    "reagent_1_rarity": "Common",
    "reagent_2": "Phosphorous",
    "reagent_2_qty": 1,
    "reagent_2_rarity": "Common",
    "reagent_3": "Phosphorous",
    "reagent_3_qty": 1,
    "reagent_3_rarity": "Common",
    "reagent_4": "Verbaena",
    "reagent_4_qty": 1,
    "reagent_4_rarity": "Common",
    "reagent_5": "Dragon's Eye",
    "value_copper": 54,
    "value_silver": 5,
    "value_gold": 0,
}

CUBS_DECOCTION = {
    "typeclass": "typeclasses.objects.ConsumableObject",
    "key": "Cub's Decoction",
    "aliases": ["cub's decoction"],
    "craft_source": "apothecary",
    "substance_type": "apotheca",
    "level": 1,
    "effect": "Add 1 temporary point of Tough to total Armor Value. Must be used before any purchased levels of Tough. This potion’s effects are canceled the next time the player uses Tough or the event ends. Does not stack with itself or other consumables that grant Tough.",
    "fee_silver": 3,
    "qty_produced": 3,
    "reagent_1": "Distilled Spirits",
    "reagent_1_qty": 2,
    "reagent_1_rarity": "Common",
    "reagent_2": "Sayge",
    "reagent_2_qty": 1,
    "reagent_2_rarity": "Common",
    "reagent_3": "Willow Root",
    "reagent_3_qty": 1,
    "reagent_3_rarity": "Common",
    "reagent_4": "Phosphorous",
    "reagent_4_qty": 1,
    "reagent_4_rarity": "Common",
    "reagent_5": "Merchant's Leaf",
    "value_copper": 54,
    "value_silver": 5,
    "value_gold": 0,
}

DISTILLED_SPIRITS = {
    "typeclass": "typeclasses.objects.ConsumableObject",
    "key": "Distilled Spirits",
    "aliases": ["distilled spirits"],
    "craft_source": "apothecary",
    "substance_type": "apotheca",
    "level": 1,
    "effect": "Base substance needed to create most any apothecary substance.",
    "fee_silver": 0,
    "qty_produced": 1,
    "reagent_1": "Distilled Spirits",
    "reagent_1_qty": 0,
    "reagent_1_rarity": "",
    "value_copper": 0,
    "value_silver": 0,
    "value_gold": 0,
}

DUELISTS_DECOCTION = {
    "typeclass": "typeclasses.objects.ConsumableObject",
    "key": "Duelist's Decoction",
    "aliases": ["duelist's decoction"],
    "craft_source": "apothecary",
    "substance_type": "apotheca",
    "level": 1,
    "effect": "Convert any one Active Martial call into a Disarm. This potion’s effects are canceled the next time the player uses the Disarm effect or the event ends. Does not stack with itself or other consumables that grant Disarm.",
    "fee_silver": 1,
    "qty_produced": 1,
    "reagent_1": "Distilled Spirits",
    "reagent_1_qty": 1,
    "reagent_1_rarity": "Common",
    "reagent_2": "Dragon's Eye",
    "reagent_2_qty": 2,
    "reagent_2_rarity": "Common",
    "reagent_3": "Sayge",
    "reagent_3_qty": 1,
    "reagent_3_rarity": "Common",
    "reagent_4": "Verbaena",
    "reagent_4_qty": 1,
    "reagent_4_rarity": "Common",
    "reagent_5": "Dragon's Eye",
    "value_copper": 52,
    "value_silver": 5,
    "value_gold": 0,
}

EAGLE = {
    "typeclass": "typeclasses.objects.ConsumableObject",
    "key": "Eagle",
    "aliases": ["eagle"],
    "craft_source": "apothecary",
    "substance_type": "apotheca",
    "level": 1,
    "effect": "Gain 1 temporary level of the Tracking Skill (Max 3) until a different potion is consumed or 30 minutes have passed. Does not stack with itself or other consumables that grant Tracking.",
    "fee_silver": 4,
    "qty_produced": 4,
    "reagent_1": "Distilled Spirits",
    "reagent_1_qty": 1,
    "reagent_1_rarity": "Common",
    "reagent_2": "Gold Lotus",
    "reagent_2_qty": 2,
    "reagent_2_rarity": "Common",
    "reagent_3": "Orgonnian Grapes",
    "reagent_3_qty": 1,
    "reagent_3_rarity": "Common",
    "reagent_4": "Orgonnian Grapes",
    "reagent_4_qty": 1,
    "reagent_4_rarity": "Common",
    "reagent_5": "Verbaena",
    "value_copper": 55,
    "value_silver": 5,
    "value_gold": 0,
}

INNISS_SERUM = {
    "typeclass": "typeclasses.objects.ConsumableObject",
    "key": "Innis's Serum",
    "aliases": ["innis's serum"],
    "craft_source": "apothecary",
    "substance_type": "apotheca",
    "level": 1,
    "effect": "Cures the Bridgit's Revenge Poison",
    "fee_silver": 2,
    "qty_produced": 2,
    "reagent_1": "Distilled Spirits",
    "reagent_1_qty": 2,
    "reagent_1_rarity": "Common",
    "reagent_2": "Orgonnian Grapes",
    "reagent_2_qty": 1,
    "reagent_2_rarity": "Common",
    "reagent_3": "Dragon's Eye",
    "reagent_3_qty": 1,
    "reagent_3_rarity": "Common",
    "reagent_4": "Celandine",
    "reagent_4_qty": 1,
    "reagent_4_rarity": "Common",
    "reagent_5": "Celandine",
    "value_copper": 53,
    "value_silver": 5,
    "value_gold": 0,
}

LILLYWHITE = {
    "typeclass": "typeclasses.objects.ConsumableObject",
    "key": "Lillywhite",
    "aliases": ["lillywhite"],
    "craft_source": "apothecary",
    "substance_type": "apotheca",
    "level": 1,
    "effect": "Cure for the Measles disease.",
    "fee_silver": 0,
    "qty_produced": 0,
    "reagent_1": "Distilled Spirits",
    "reagent_1_qty": 1,
    "reagent_1_rarity": "Common",
    "reagent_2": "Dragon's Eye",
    "reagent_2_qty": 1,
    "reagent_2_rarity": "Common",
    "reagent_3": "Verbaena",
    "reagent_3_qty": 1,
    "reagent_3_rarity": "Common",
    "reagent_4": "Willow Root",
    "reagent_4_qty": 2,
    "reagent_4_rarity": "Common",
    "reagent_5": "Celandine",
    "value_copper": 52,
    "value_silver": 5,
    "value_gold": 0,
}

MOONBREW = {
    "typeclass": "typeclasses.objects.ConsumableObject",
    "key": "Moonbrew",
    "aliases": ["moonbrew"],
    "craft_source": "apothecary",
    "substance_type": "apotheca",
    "level": 1,
    "effect": "This rare remedy is one of the few curatives for an infection of otherworldly fungus known as Funeral Bell, found in the Annwyn. This flora insidiously infects its victim, slowly turning them into a mindless, ravenous automation that only seeks to spread the affliction. When consumed, this semi-toxic decoction produces vomiting, muscle spasms, and nausea that violently expels the infestation.",
    "fee_silver": 1,
    "qty_produced": 1,
    "reagent_1": "Distilled Spirits",
    "reagent_1_qty": 1,
    "reagent_1_rarity": "Common",
    "reagent_2": "Gold Lotus",
    "reagent_2_qty": 1,
    "reagent_2_rarity": "Common",
    "reagent_3": "Phosphorous",
    "reagent_3_qty": 1,
    "reagent_3_rarity": "Common",
    "reagent_4": "Mandrake",
    "reagent_4_qty": 1,
    "reagent_4_rarity": "Common",
    "reagent_5": "Mandrake",
    "value_copper": 42,
    "value_silver": 4,
    "value_gold": 0,
}

PIT_FIGHTERS_ELIXIR = {
    "typeclass": "typeclasses.objects.ConsumableObject",
    "key": "Pit Fighter's Elixir",
    "aliases": ["pit fighter's elixir"],
    "craft_source": "apothecary",
    "substance_type": "apotheca",
    "level": 1,
    "effect": "Convert any one Active Martial call into a Stun, and the Stun does not require an attack from behind. This potion’s effects are canceled the next time the player uses a Stun effect or the event ends. Does not stack with itself or other consumables that grant Stun.",
    "fee_silver": 2,
    "qty_produced": 2,
    "reagent_1": "Distilled Spirits",
    "reagent_1_qty": 1,
    "reagent_1_rarity": "Common",
    "reagent_2": "Dragon's Eye",
    "reagent_2_qty": 1,
    "reagent_2_rarity": "Common",
    "reagent_3": "Verbaena",
    "reagent_3_qty": 1,
    "reagent_3_rarity": "Common",
    "reagent_4": "Phosphorous",
    "reagent_4_qty": 1,
    "reagent_4_rarity": "Common",
    "reagent_5": "Willow Root",
    "value_copper": 43,
    "value_silver": 4,
    "value_gold": 0,
}

PURITY_DECOCTION = {
    "typeclass": "typeclasses.objects.ConsumableObject",
    "key": "Purity Decoction",
    "aliases": ["purity decoction"],
    "craft_source": "apothecary",
    "substance_type": "apotheca",
    "level": 1,
    "effect": "Cure for the Lilting Plague disease.",
    "fee_silver": 1,
    "qty_produced": 1,
    "reagent_1": "Distilled Spirits",
    "reagent_1_qty": 2,
    "reagent_1_rarity": "Common",
    "reagent_2": "Celandine",
    "reagent_2_qty": 1,
    "reagent_2_rarity": "Common",
    "reagent_3": "Luminesce",
    "reagent_3_qty": 1,
    "reagent_3_rarity": "Common",
    "reagent_4": "Phosphorous",
    "reagent_4_qty": 1,
    "reagent_4_rarity": "Common",
    "reagent_5": "Black Salt",
    "value_copper": 52,
    "value_silver": 5,
    "value_gold": 0,
}

SPOTTERS_DRAUGHT = {
    "typeclass": "typeclasses.objects.ConsumableObject",
    "key": "Spotter's Draught",
    "aliases": ["spotter's draught"],
    "craft_source": "apothecary",
    "substance_type": "apotheca",
    "level": 1,
    "effect": "Gain 1 temporary level of the Perception Skill (Max 3) until a different potion is consumed or 30 minutes have passed. Does not stack with itself or other consumables that grant Perception.",
    "fee_silver": 2,
    "qty_produced": 2,
    "reagent_1": "Distilled Spirits",
    "reagent_1_qty": 1,
    "reagent_1_rarity": "Common",
    "reagent_2": "Orgonnian Grapes",
    "reagent_2_qty": 1,
    "reagent_2_rarity": "Common",
    "reagent_3": "Orgonnian Grapes",
    "reagent_3_qty": 1,
    "reagent_3_rarity": "Common",
    "reagent_4": "Verbaena",
    "reagent_4_qty": 1,
    "reagent_4_rarity": "Common",
    "reagent_5": "Verbaena",
    "value_copper": 43,
    "value_silver": 4,
    "value_gold": 0,
}

VERDANT_DECOCTION = {
    "typeclass": "typeclasses.objects.ConsumableObject",
    "key": "Verdant Decoction",
    "aliases": ["verdant decoction"],
    "craft_source": "apothecary",
    "substance_type": "apotheca",
    "level": 1,
    "effect": "Cure for the Graverot Fever disease.",
    "fee_silver": 4,
    "qty_produced": 4,
    "reagent_1": "Distilled Spirits",
    "reagent_1_qty": 2,
    "reagent_1_rarity": "Common",
    "reagent_2": "Celandine",
    "reagent_2_qty": 1,
    "reagent_2_rarity": "Common",
    "reagent_3": "Hollyrue",
    "reagent_3_qty": 1,
    "reagent_3_rarity": "Common",
    "reagent_4": "Sayge",
    "reagent_4_qty": 1,
    "reagent_4_rarity": "Common",
    "reagent_5": "Willow Root",
    "value_copper": 55,
    "value_silver": 5,
    "value_gold": 0,
}

WHITE_ROLANDS_SERUM = {
    "typeclass": "typeclasses.objects.ConsumableObject",
    "key": "White Roland's Serum",
    "aliases": ["white roland's serum"],
    "craft_source": "apothecary",
    "substance_type": "apotheca",
    "level": 1,
    "effect": "Add 60 seconds to your Bleeding Count. May only be used while in the Bleeding Count. Does not stack with itself or other consumables that grant seconds to the Bleeding Count.",
    "fee_silver": 1,
    "qty_produced": 1,
    "reagent_1": "Distilled Spirits",
    "reagent_1_qty": 1,
    "reagent_1_rarity": "Common",
    "reagent_2": "Phosphorous",
    "reagent_2_qty": 2,
    "reagent_2_rarity": "Common",
    "reagent_3": "Merchant's Leaf",
    "reagent_3_qty": 1,
    "reagent_3_rarity": "Common",
    "reagent_4": "Phosphorous",
    "reagent_4_qty": 1,
    "reagent_4_rarity": "Common",
    "reagent_5": "Willow Root",
    "value_copper": 52,
    "value_silver": 5,
    "value_gold": 0,
}

# ==== Level 1 Poison ====

BRIDGITS_REVENGE = {
    "typeclass": "typeclasses.objects.ConsumableObject",
    "key": "Bridgit's Revenge",
    "aliases": ["bridgit's revenge"],
    "craft_source": "apothecary",
    "substance_type": "poison",
    "level": 1,
    "effect": "Bridgit’s Revenge causes immediate and severe stomach pains, vomiting, and sometimes internal bleeding. If not cured, the poison progresses into a painful infection which slowly kills the victim after about three months. The poison causes the Weakness effect at the second event with the infection, and the victim dies at the end of their second event if not cured.",
    "fee_silver": 2,
    "qty_produced": 2,
    "reagent_1": "Distilled Spirits",
    "reagent_1_qty": 1,
    "reagent_1_rarity": "Uncommon",
    "reagent_2": "Thornwood Fern",
    "reagent_2_qty": 1,
    "reagent_2_rarity": "Uncommon",
    "reagent_3": "Thornwood Fern",
    "reagent_3_qty": 1,
    "reagent_3_rarity": "Uncommon",
    "reagent_4": "Thornwood Fern",
    "reagent_4_qty": 2,
    "reagent_4_rarity": "Common",
    "reagent_5": "Verbaena",
    "value_copper": 57,
    "value_silver": 5,
    "value_gold": 0,
}

# ==== Level 1 Drug ====

CUTTER = {
    "typeclass": "typeclasses.objects.ConsumableObject",
    "key": "Cutter",
    "aliases": ["cutter"],
    "craft_source": "apothecary",
    "substance_type": "drug",
    "level": 1,
    "effect": "Cutter is a fine white powder that is highly stimulating and causes extreme attentiveness and agitation for 1 hour. Gain 1 temporary level of the Perception skill (max 3) and -1 minute to Bleeding count for duration. Does not stack with itself or other consumables that grant Perception. This drug is highly addictive and should be roleplayed as such.",
    "fee_silver": 0,
    "qty_produced": 0,
    "reagent_1": "Distilled Spirits",
    "reagent_1_qty": 1,
    "reagent_1_rarity": "Common",
    "reagent_2": "Merchant's Leaf",
    "reagent_2_qty": 2,
    "reagent_2_rarity": "Common",
    "reagent_3": "Merchant's Leaf",
    "reagent_3_qty": 1,
    "reagent_3_rarity": "Common",
    "reagent_4": "Verbaena",
    "reagent_4_qty": 1,
    "reagent_4_rarity": "Common",
    "reagent_5": "Verbaena",
    "value_copper": 51,
    "value_silver": 5,
    "value_gold": 0,
}

SPICE = {
    "typeclass": "typeclasses.objects.ConsumableObject",
    "key": "Spice",
    "aliases": ["spice"],
    "craft_source": "apothecary",
    "substance_type": "drug",
    "level": 1,
    "effect": "An intense hallucinogenic. The user must have at least Academics 1 to gain the following benefit: May ignore all level 1 lore requirements to open and read lores for ten minutes. Cannot use those lores to level up if they do not meet the standard requirement yet; but they can hold on to the lores and use them later when they do. Academics reduced to 0 for one hour afterwards.",
    "fee_silver": 2,
    "qty_produced": 2,
    "reagent_1": "Distilled Spirits",
    "reagent_1_qty": 1,
    "reagent_1_rarity": "Common",
    "reagent_2": "Sayge",
    "reagent_2_qty": 2,
    "reagent_2_rarity": "Common",
    "reagent_3": "Gold Lotus",
    "reagent_3_qty": 1,
    "reagent_3_rarity": "Common",
    "reagent_4": "Mandrake",
    "reagent_4_qty": 1,
    "reagent_4_rarity": "Common",
    "reagent_5": "Mandrake",
    "value_copper": 53,
    "value_silver": 5,
    "value_gold": 0,
}

STARDUST = {
    "typeclass": "typeclasses.objects.ConsumableObject",
    "key": "Stardust",
    "aliases": ["stardust"],
    "craft_source": "apothecary",
    "substance_type": "drug",
    "level": 1,
    "effect": "Renders a state of blissful, numb euphoria for 1 hour. During that time, the user is hardly able to rouse themselves from their dreamlike state. Gain 1 temporary point of Tough and the Weakness effect for the duration. Does not stack with itself or other consumables that grant Tough. This drug is moderately addictive and should be roleplayed as such.",
    "fee_silver": 0,
    "qty_produced": 0,
    "reagent_1": "Distilled Spirits",
    "reagent_1_qty": 1,
    "reagent_1_rarity": "Common",
    "reagent_2": "Mandrake",
    "reagent_2_qty": 1,
    "reagent_2_rarity": "Common",
    "reagent_3": "Mandrake",
    "reagent_3_qty": 2,
    "reagent_3_rarity": "Common",
    "reagent_4": "Willow Root",
    "reagent_4_qty": 1,
    "reagent_4_rarity": "Common",
    "reagent_5": "Verbaena",
    "value_copper": 51,
    "value_silver": 5,
    "value_gold": 0,
}

# ==== Level 2 Apotheca ====

BEARS_DECOCTION = {
    "typeclass": "typeclasses.objects.ConsumableObject",
    "key": "Bear's Decoction",
    "aliases": ["bear's decoction"],
    "craft_source": "apothecary",
    "substance_type": "apotheca",
    "level": 2,
    "effect": "Add 2 temporary points of Tough to total Armor Value. Must be used before any purchased levels of Tough. This potion’s effects are canceled the next time the player uses both temporary Tough points or the event ends. Does not stack with itself or other consumables that grant Tough.",
    "fee_silver": 2,
    "qty_produced": 2,
    "reagent_1": "Distilled Spirits",
    "reagent_1_qty": 3,
    "reagent_1_rarity": "Common",
    "reagent_2": "Phosphorous",
    "reagent_2_qty": 2,
    "reagent_2_rarity": "Common",
    "reagent_3": "Verbaena",
    "reagent_3_qty": 3,
    "reagent_3_rarity": "Uncommon",
    "reagent_4": "Wintercrown",
    "reagent_4_qty": 2,
    "reagent_4_rarity": "Uncommon",
    "reagent_5": "Ergot Seeds",
    "value_copper": 112,
    "value_silver": 11,
    "value_gold": 1,
}

EXPERT_BLADE_OIL = {
    "typeclass": "typeclasses.objects.ConsumableObject",
    "key": "Expert Blade Oil",
    "aliases": ["expert blade oil"],
    "craft_source": "apothecary",
    "substance_type": "apotheca",
    "level": 2,
    "effect": "Applied to a weapon to convert any two calls into Cleaves and allows the skill to be used with 1-Handed weapons. This potion’s effects are canceled the next time the player uses both Cleave effects or the event ends. A weapon can only have one oil/salve on it at a time.",
    "fee_silver": 6,
    "qty_produced": 6,
    "reagent_1": "Distilled Spirits",
    "reagent_1_qty": 1,
    "reagent_1_rarity": "Common",
    "reagent_2": "Dragon's Eye",
    "reagent_2_qty": 1,
    "reagent_2_rarity": "Uncommon",
    "reagent_3": "Crypt Moss",
    "reagent_3_qty": 1,
    "reagent_3_rarity": "Common",
    "reagent_4": "Willow Root",
    "reagent_4_qty": 3,
    "reagent_4_rarity": "Common",
    "reagent_5": "Dragon's Eye",
    "value_copper": 73,
    "value_silver": 7,
    "value_gold": 0,
}

EXPERT_BLADE_SALVE = {
    "typeclass": "typeclasses.objects.ConsumableObject",
    "key": "Expert Blade Salve",
    "aliases": ["expert blade salve"],
    "craft_source": "apothecary",
    "substance_type": "apotheca",
    "level": 2,
    "effect": "Applied to a weapon to allow it to absorb 2 additional Sunders. This effect lasts until the weapon is Sundered twice or the event ends. A weapon can only have one oil/salve on it at a time.",
    "fee_silver": 3,
    "qty_produced": 3,
    "reagent_1": "Distilled Spirits",
    "reagent_1_qty": 2,
    "reagent_1_rarity": "Common",
    "reagent_2": "Sayge",
    "reagent_2_qty": 2,
    "reagent_2_rarity": "Common",
    "reagent_3": "Willow Root",
    "reagent_3_qty": 2,
    "reagent_3_rarity": "Common",
    "reagent_4": "Verbaena",
    "reagent_4_qty": 1,
    "reagent_4_rarity": "Uncommon",
    "reagent_5": "Duskland Rose",
    "value_copper": 77,
    "value_silver": 7,
    "value_gold": 0,
}

EXPERT_DUELISTS_DECOCTION = {
    "typeclass": "typeclasses.objects.ConsumableObject",
    "key": "Expert Duelist's Decoction",
    "aliases": ["expert duelist's decoction"],
    "craft_source": "apothecary",
    "substance_type": "apotheca",
    "level": 2,
    "effect": "Convert any two Active Martial calls into Disarms. This potion’s effects are canceled the next time the player uses both Disarm effects or the event ends. Does not stack with itself or other consumables that grant Disarm.",
    "fee_silver": 4,
    "qty_produced": 4,
    "reagent_1": "Distilled Spirits",
    "reagent_1_qty": 2,
    "reagent_1_rarity": "Uncommon",
    "reagent_2": "Ergot Seeds",
    "reagent_2_qty": 2,
    "reagent_2_rarity": "Common",
    "reagent_3": "Sayge",
    "reagent_3_qty": 1,
    "reagent_3_rarity": "Common",
    "reagent_4": "Dragon's Eye",
    "reagent_4_qty": 1,
    "reagent_4_rarity": "Uncommon",
    "reagent_5": "Wraith Orchid",
    "value_copper": 70,
    "value_silver": 7,
    "value_gold": 0,
}

FALCON = {
    "typeclass": "typeclasses.objects.ConsumableObject",
    "key": "Falcon",
    "aliases": ["falcon"],
    "craft_source": "apothecary",
    "substance_type": "apotheca",
    "level": 2,
    "effect": "Gain 2 temporary levels of the Tracking Skill (Max 3) until a different potion is consumed or 1 hour has passed. Does not stack with itself or other consumables that grant Tracking.",
    "fee_silver": 4,
    "qty_produced": 4,
    "reagent_1": "Distilled Spirits",
    "reagent_1_qty": 2,
    "reagent_1_rarity": "Common",
    "reagent_2": "Orgonnian Grapes",
    "reagent_2_qty": 2,
    "reagent_2_rarity": "Uncommon",
    "reagent_3": "Creeper Moss",
    "reagent_3_qty": 1,
    "reagent_3_rarity": "Uncommon",
    "reagent_4": "Harrowdust",
    "reagent_4_qty": 1,
    "reagent_4_rarity": "Uncommon",
    "reagent_5": "Wraith Orchid",
    "value_copper": 71,
    "value_silver": 7,
    "value_gold": 0,
}

GORGONS_BREW = {
    "typeclass": "typeclasses.objects.ConsumableObject",
    "key": "Gorgon's Brew",
    "aliases": ["gorgon's brew"],
    "craft_source": "apothecary",
    "substance_type": "apotheca",
    "level": 2,
    "effect": "Convert any two Active Martial calls into Sunders, and allows the skill to be used with any 1-Handed weapon. This potion’s effects are canceled the next time the player uses both Sunder effects or the event ends. Does not stack with itself or other consumables that grant Sunder.",
    "fee_silver": 6,
    "qty_produced": 6,
    "reagent_1": "Distilled Spirits",
    "reagent_1_qty": 1,
    "reagent_1_rarity": "Uncommon",
    "reagent_2": "Crypt Moss",
    "reagent_2_qty": 1,
    "reagent_2_rarity": "Uncommon",
    "reagent_3": "Ergot Seeds",
    "reagent_3_qty": 2,
    "reagent_3_rarity": "Common",
    "reagent_4": "Gold Lotus",
    "reagent_4_qty": 2,
    "reagent_4_rarity": "Common",
    "reagent_5": "Phosphorous",
    "value_copper": 72,
    "value_silver": 7,
    "value_gold": 0,
}

LASTING_BREATH = {
    "typeclass": "typeclasses.objects.ConsumableObject",
    "key": "Lasting Breath",
    "aliases": ["lasting breath"],
    "craft_source": "apothecary",
    "substance_type": "apotheca",
    "level": 2,
    "effect": "Add 120 seconds to Bleeding Count. May only be used while in the Bleeding Count. Does not stack with itself or other consumables that grant seconds to the Bleeding Count.",
    "fee_silver": 2,
    "qty_produced": 2,
    "reagent_1": "Distilled Spirits",
    "reagent_1_qty": 2,
    "reagent_1_rarity": "Uncommon",
    "reagent_2": "Thornwood Fern",
    "reagent_2_qty": 3,
    "reagent_2_rarity": "Common",
    "reagent_3": "Willow Root",
    "reagent_3_qty": 2,
    "reagent_3_rarity": "Common",
    "reagent_4": "Phosphorous",
    "reagent_4_qty": 1,
    "reagent_4_rarity": "Uncommon",
    "reagent_5": "Wintercrown",
    "value_copper": 88,
    "value_silver": 8,
    "value_gold": 0,
}

LOOKOUT = {
    "typeclass": "typeclasses.objects.ConsumableObject",
    "key": "Lookout",
    "aliases": ["lookout"],
    "craft_source": "apothecary",
    "substance_type": "apotheca",
    "level": 2,
    "effect": "Gain 2 temporary levels of the Perception Skill (Max 3) until a different potion is consumed or 1 hour has passed. Does not stack with itself or other consumables that grant Perception.",
    "fee_silver": 3,
    "qty_produced": 3,
    "reagent_1": "Distilled Spirits",
    "reagent_1_qty": 1,
    "reagent_1_rarity": "Uncommon",
    "reagent_2": "Tarkathi Poppy",
    "reagent_2_qty": 1,
    "reagent_2_rarity": "Uncommon",
    "reagent_3": "Harrowdust",
    "reagent_3_qty": 4,
    "reagent_3_rarity": "Common",
    "reagent_4": "Orgonnian Grapes",
    "reagent_4_qty": 1,
    "reagent_4_rarity": "Uncommon",
    "reagent_5": "Wraith Orchid",
    "value_copper": 79,
    "value_silver": 7,
    "value_gold": 0,
}

MENDER = {
    "typeclass": "typeclasses.objects.ConsumableObject",
    "key": "Mender",
    "aliases": ["mender"],
    "craft_source": "apothecary",
    "substance_type": "apotheca",
    "level": 2,
    "effect": "Cure Paralyze",
    "fee_silver": 8,
    "qty_produced": 8,
    "reagent_1": "Distilled Spirits",
    "reagent_1_qty": 2,
    "reagent_1_rarity": "Uncommon",
    "reagent_2": "Wraith Orchid",
    "reagent_2_qty": 1,
    "reagent_2_rarity": "Uncommon",
    "reagent_3": "Wraith Orchid",
    "reagent_3_qty": 2,
    "reagent_3_rarity": "Common",
    "reagent_4": "Black Salt",
    "reagent_4_qty": 2,
    "reagent_4_rarity": "Common",
    "reagent_5": "Hollyrue",
    "value_copper": 85,
    "value_silver": 8,
    "value_gold": 0,
}

NYRAS_BALM = {
    "typeclass": "typeclasses.objects.ConsumableObject",
    "key": "Nyra's Balm",
    "aliases": ["nyra's balm"],
    "craft_source": "apothecary",
    "substance_type": "apotheca",
    "level": 2,
    "effect": "The cure for Weeping Sickness, discovered by Magister Nyra in the Sirat of Serapis where she was known to aid the less fortunate who would so often succumb to the illness. This paste soothes and cures the sores of the sickness.",
    "fee_silver": 1,
    "qty_produced": 1,
    "reagent_1": "Distilled Spirits",
    "reagent_1_qty": 1,
    "reagent_1_rarity": "Uncommon",
    "reagent_2": "Tarkathi Poppy",
    "reagent_2_qty": 2,
    "reagent_2_rarity": "Uncommon",
    "reagent_3": "Blood Medallion",
    "reagent_3_qty": 2,
    "reagent_3_rarity": "Uncommon",
    "reagent_4": "Wintercrown",
    "reagent_4_qty": 2,
    "reagent_4_rarity": "Common",
    "reagent_5": "Sayge",
    "value_copper": 80,
    "value_silver": 8,
    "value_gold": 0,
}

PUISSANCE_DRAUGHT = {
    "typeclass": "typeclasses.objects.ConsumableObject",
    "key": "Puissance Draught",
    "aliases": ["puissance draught"],
    "craft_source": "apothecary",
    "substance_type": "apotheca",
    "level": 2,
    "effect": "Gain 1 temporary use of Resist. This potion’s effects are canceled the next time the player uses a Resist or the event ends. Does not stack with itself or other consumables that grant Resist.",
    "fee_silver": 2,
    "qty_produced": 2,
    "reagent_1": "Distilled Spirits",
    "reagent_1_qty": 2,
    "reagent_1_rarity": "Uncommon",
    "reagent_2": "Duskland Rose",
    "reagent_2_qty": 2,
    "reagent_2_rarity": "Common",
    "reagent_3": "Luminesce",
    "reagent_3_qty": 2,
    "reagent_3_rarity": "Common",
    "reagent_4": "Hollyrue",
    "reagent_4_qty": 1,
    "reagent_4_rarity": "Uncommon",
    "reagent_5": "Amber Lichen",
    "value_copper": 78,
    "value_silver": 7,
    "value_gold": 0,
}

ELIXIR_OF_THE_WANING_MOON = {
    "typeclass": "typeclasses.objects.ConsumableObject",
    "key": "Elixir of the Waning Moon",
    "aliases": ["elixir of the waning moon"],
    "craft_source": "apothecary",
    "substance_type": "apotheca",
    "level": 2,
    "effect": "Cure Lycanthropic Infection",
    "fee_silver": 5,
    "qty_produced": 5,
    "reagent_1": "Distilled Spirits",
    "reagent_1_qty": 2,
    "reagent_1_rarity": "Uncommon",
    "reagent_2": "Amber Lichen",
    "reagent_2_qty": 1,
    "reagent_2_rarity": "Loot Drop",
    "reagent_3": "Werewolf Tallow",
    "reagent_3_qty": 3,
    "reagent_3_rarity": "Common",
    "reagent_4": "Willow Root",
    "reagent_4_qty": 2,
    "reagent_4_rarity": "Uncommon",
    "reagent_5": "Ergot Seeds",
    "value_copper": 164,
    "value_silver": 16,
    "value_gold": 1,
}

RESURGENCE = {
    "typeclass": "typeclasses.objects.ConsumableObject",
    "key": "Resurgence",
    "aliases": ["resurgence"],
    "craft_source": "apothecary",
    "substance_type": "apotheca",
    "level": 2,
    "effect": "Immediately stop Bleeding Count. May only be used while in the Bleeding Count. All Death & Dying rules apply after stopping the Bleeding Count (i.e. you enter the Wounded State).",
    "fee_silver": 3,
    "qty_produced": 3,
    "reagent_1": "Distilled Spirits",
    "reagent_1_qty": 1,
    "reagent_1_rarity": "Uncommon",
    "reagent_2": "Thornwood Fern",
    "reagent_2_qty": 1,
    "reagent_2_rarity": "Common",
    "reagent_3": "Dragon's Eye",
    "reagent_3_qty": 1,
    "reagent_3_rarity": "Rare",
    "reagent_4": "Grave Blood",
    "reagent_4_qty": 1,
    "reagent_4_rarity": "Loot Drop",
    "reagent_5": "Spirit Essence",
    "value_copper": 162,
    "value_silver": 16,
    "value_gold": 1,
}

SLAYER = {
    "typeclass": "typeclasses.objects.ConsumableObject",
    "key": "Slayer",
    "aliases": ["slayer"],
    "craft_source": "apothecary",
    "substance_type": "apotheca",
    "level": 2,
    "effect": "Convert any two Active Martial calls into Staggers. This potion’s effects are canceled the next time the player uses both Stagger effects or the event ends. Does not stack with itself or other consumables that grant Stagger.",
    "fee_silver": 3,
    "qty_produced": 3,
    "reagent_1": "Distilled Spirits",
    "reagent_1_qty": 1,
    "reagent_1_rarity": "Common",
    "reagent_2": "Dragon's Eye",
    "reagent_2_qty": 2,
    "reagent_2_rarity": "Uncommon",
    "reagent_3": "Crypt Moss",
    "reagent_3_qty": 2,
    "reagent_3_rarity": "Common",
    "reagent_4": "Phosphorous",
    "reagent_4_qty": 2,
    "reagent_4_rarity": "Common",
    "reagent_5": "Phosphorous",
    "value_copper": 79,
    "value_silver": 7,
    "value_gold": 0,
}

STUNNER = {
    "typeclass": "typeclasses.objects.ConsumableObject",
    "key": "Stunner",
    "aliases": ["stunner"],
    "craft_source": "apothecary",
    "substance_type": "apotheca",
    "level": 2,
    "effect": "Convert any two Active Martial calls into Stuns, and the Stuns do not require an attack from behind. This potion’s effects are canceled the next time the player uses both Stun effects or the event ends. Does not stack with itself or other consumables that grant Stun.",
    "fee_silver": 3,
    "qty_produced": 3,
    "reagent_1": "Distilled Spirits",
    "reagent_1_qty": 2,
    "reagent_1_rarity": "Uncommon",
    "reagent_2": "Wintercrown",
    "reagent_2_qty": 2,
    "reagent_2_rarity": "Common",
    "reagent_3": "Luminesce",
    "reagent_3_qty": 2,
    "reagent_3_rarity": "Common",
    "reagent_4": "Sayge",
    "reagent_4_qty": 1,
    "reagent_4_rarity": "Common",
    "reagent_5": "Sayge",
    "value_copper": 77,
    "value_silver": 7,
    "value_gold": 0,
}

SUNRISE_DECOCTION = {
    "typeclass": "typeclasses.objects.ConsumableObject",
    "key": "Sunrise Decoction",
    "aliases": ["sunrise decoction"],
    "craft_source": "apothecary",
    "substance_type": "apotheca",
    "level": 2,
    "effect": "Immediately cure the Weakness effect. Does not cure weakness granted by the wounded state.",
    "fee_silver": 4,
    "qty_produced": 4,
    "reagent_1": "Distilled Spirits",
    "reagent_1_qty": 1,
    "reagent_1_rarity": "Uncommon",
    "reagent_2": "Wraith Orchid",
    "reagent_2_qty": 2,
    "reagent_2_rarity": "Uncommon",
    "reagent_3": "Ergot Seeds",
    "reagent_3_qty": 2,
    "reagent_3_rarity": "Common",
    "reagent_4": "Black Salt",
    "reagent_4_qty": 2,
    "reagent_4_rarity": "Common",
    "reagent_5": "Dragon's Eye",
    "value_copper": 81,
    "value_silver": 8,
    "value_gold": 0,
}

SWINDLERS_BREW = {
    "typeclass": "typeclasses.objects.ConsumableObject",
    "key": "Swindler's Brew",
    "aliases": ["swindler's brew"],
    "craft_source": "apothecary",
    "substance_type": "apotheca",
    "level": 2,
    "effect": "Gain 2 temporary levels of the Disarm Device skill (Max 3) until a different potion is consumed or 1 hour has passed. Does not stack with itself or other consumables that grant Disarm Device.",
    "fee_silver": 5,
    "qty_produced": 5,
    "reagent_1": "Distilled Spirits",
    "reagent_1_qty": 2,
    "reagent_1_rarity": "Uncommon",
    "reagent_2": "Duskland Rose",
    "reagent_2_qty": 1,
    "reagent_2_rarity": "Uncommon",
    "reagent_3": "Amber Lichen",
    "reagent_3_qty": 2,
    "reagent_3_rarity": "Common",
    "reagent_4": "Hollyrue",
    "reagent_4_qty": 1,
    "reagent_4_rarity": "Common",
    "reagent_5": "Sayge",
    "value_copper": 70,
    "value_silver": 7,
    "value_gold": 0,
}

URSINS_STRENGTH = {
    "typeclass": "typeclasses.objects.ConsumableObject",
    "key": "Ursin's Strength",
    "aliases": ["ursin's strength"],
    "craft_source": "apothecary",
    "substance_type": "apotheca",
    "level": 2,
    "effect": "Antidote to the Broth of the Volkun poison.",
    "fee_silver": 2,
    "qty_produced": 2,
    "reagent_1": "Distilled Spirits",
    "reagent_1_qty": 4,
    "reagent_1_rarity": "Uncommon",
    "reagent_2": "Wintercrown",
    "reagent_2_qty": 2,
    "reagent_2_rarity": "Uncommon",
    "reagent_3": "Red Lotus",
    "reagent_3_qty": 1,
    "reagent_3_rarity": "Uncommon",
    "reagent_4": "Wraith Orchid",
    "reagent_4_qty": 2,
    "reagent_4_rarity": "Common",
    "reagent_5": "Verbaena",
    "value_copper": 103,
    "value_silver": 10,
    "value_gold": 0,
}

# ==== Level 2 Poison ====

BROTH_OF_THE_VOLKUN = {
    "typeclass": "typeclasses.objects.ConsumableObject",
    "key": "Broth of the Volkun",
    "aliases": ["broth of the volkun"],
    "craft_source": "apothecary",
    "substance_type": "poison",
    "level": 2,
    "effect": "Causes immediate, uncurable Weakness. Over the course of 24 hours, the victim becomes weaker and weaker, as their bones become brittle and unable to support themselves. Bones may break easily. At the 12 hour mark, the victim will start to suffer from random episodes of paralysis that last for 15 minutes but are curable. If not cured of the poison, the victim dies 24 hours after imbibing.",
    "fee_silver": 4,
    "qty_produced": 4,
    "reagent_1": "Distilled Spirits",
    "reagent_1_qty": 5,
    "reagent_1_rarity": "Uncommon",
    "reagent_2": "Creeper Moss",
    "reagent_2_qty": 3,
    "reagent_2_rarity": "Uncommon",
    "reagent_3": "Red Lotus",
    "reagent_3_qty": 1,
    "reagent_3_rarity": "Common",
    "reagent_4": "Mandrake",
    "reagent_4_qty": 1,
    "reagent_4_rarity": "Common",
    "reagent_5": "Mandrake",
    "value_copper": 114,
    "value_silver": 11,
    "value_gold": 0,
}

GRAVEDIGGER = {
    "typeclass": "typeclasses.objects.ConsumableObject",
    "key": "Gravedigger",
    "aliases": ["gravedigger"],
    "craft_source": "apothecary",
    "substance_type": "poison",
    "level": 2,
    "effect": "Said to be concocted for a wealthy merchant who wished to escape a death sentence, Gravedigger causes full body paralysis and slows the heartrate to imperceptible levels. A useful way to incapacitate your foes, or feign death and start a new life. Victim is paralyzed for 20 to 30 minutes.",
    "fee_silver": 5,
    "qty_produced": 5,
    "reagent_1": "Distilled Spirits",
    "reagent_1_qty": 1,
    "reagent_1_rarity": "Rare",
    "reagent_2": "Death's Head Cap",
    "reagent_2_qty": 3,
    "reagent_2_rarity": "Uncommon",
    "reagent_3": "Wraith Orchid",
    "reagent_3_qty": 3,
    "reagent_3_rarity": "Common",
    "reagent_4": "Mandrake",
    "reagent_4_qty": 1,
    "reagent_4_rarity": "Common",
    "reagent_5": "Black Salt",
    "value_copper": 98,
    "value_silver": 9,
    "value_gold": 0,
}

QUAGMIRE = {
    "typeclass": "typeclasses.objects.ConsumableObject",
    "key": "Quagmire",
    "aliases": ["quagmire"],
    "craft_source": "apothecary",
    "substance_type": "poison",
    "level": 2,
    "effect": "Sometimes called “Bottled Weariness”, Quagmire is a poison that causes severe sluggishness and fatigue, encouraging the victim to rest or sleep. It only lasts an hour, but that’s long enough for one’s enemies to take advantage. It is mainly used when one wishes to inflict harm, but not death. Victim gains the Weakness effect for 1 hour or until cured.",
    "fee_silver": 3,
    "qty_produced": 3,
    "reagent_1": "Distilled Spirits",
    "reagent_1_qty": 3,
    "reagent_1_rarity": "Uncommon",
    "reagent_2": "Widow's Petal",
    "reagent_2_qty": 2,
    "reagent_2_rarity": "Uncommon",
    "reagent_3": "Widow's Petal",
    "reagent_3_qty": 2,
    "reagent_3_rarity": "Common",
    "reagent_4": "Mandrake",
    "reagent_4_qty": 1,
    "reagent_4_rarity": "Common",
    "reagent_5": "Mandrake",
    "value_copper": 90,
    "value_silver": 9,
    "value_gold": 0,
}

# ==== Level 2 Drug ====

THE_GLOAMING = {
    "typeclass": "typeclasses.objects.ConsumableObject",
    "key": "The Gloaming",
    "aliases": ["the gloaming"],
    "craft_source": "apothecary",
    "substance_type": "drug",
    "level": 2,
    "effect": "This ruddy vial of brackish green liquid is to be taken just before bed. Some say it is made by blaspheming the dead, whatever that means. Upon imbibing, you are for a time seemingly transported to the consciousness of another. Alive? Long dead? Who can say? You are however, keenly aware of a body of knowledge and experiences not your own. Use the Information Gathering ability and switch a lore skill you have for another of the same level until the next refresh. The more you use this drug, you will find it increasingly difficult to maintain your sense of self and reality as fragments of other anima compete for space in your psyche. Over the course of one refresh, you experience at random one each of the effects Paralyze, Sleep, and Fear.",
    "fee_silver": 5,
    "qty_produced": 5,
    "reagent_1": "Distilled Spirits",
    "reagent_1_qty": 1,
    "reagent_1_rarity": "Loot Drop",
    "reagent_2": "Essence of the Unhallowed",
    "reagent_2_qty": 3,
    "reagent_2_rarity": "Uncommon",
    "reagent_3": "Tarkathi Poppy",
    "reagent_3_qty": 2,
    "reagent_3_rarity": "Uncommon",
    "reagent_4": "Widow's Petal",
    "reagent_4_qty": 2,
    "reagent_4_rarity": "Common",
    "reagent_5": "Luminesce",
    "value_copper": 164,
    "value_silver": 16,
    "value_gold": 0,
}

MASTER_MOONLIGHT = {
    "typeclass": "typeclasses.objects.ConsumableObject",
    "key": "Master Moonlight",
    "aliases": ["master moonlight"],
    "craft_source": "apothecary",
    "substance_type": "drug",
    "level": 2,
    "effect": "An intense hallucinogenic. The user must have at least Academics 2 to gain the following benefit: May ignore all level 2 lore requirements to open and read lores for ten minutes. Cannot use those lores to level up if they do not meet the standard requirement yet; but they can hold on to the lores and use them later when they do. Academics reduced to 0 for one hour afterwards.",
    "fee_silver": 4,
    "qty_produced": 4,
    "reagent_1": "Distilled Spirits",
    "reagent_1_qty": 3,
    "reagent_1_rarity": "Uncommon",
    "reagent_2": "Harrowdust",
    "reagent_2_qty": 1,
    "reagent_2_rarity": "Common",
    "reagent_3": "Mandrake",
    "reagent_3_qty": 1,
    "reagent_3_rarity": "Uncommon",
    "reagent_4": "Blood Medallion",
    "reagent_4_qty": 1,
    "reagent_4_rarity": "Common",
    "reagent_5": "Gold Lotus",
    "value_copper": 70,
    "value_silver": 7,
    "value_gold": 0,
}

MIRAGE = {
    "typeclass": "typeclasses.objects.ConsumableObject",
    "key": "Mirage",
    "aliases": ["mirage"],
    "craft_source": "apothecary",
    "substance_type": "drug",
    "level": 2,
    "effect": "Dried leaves that when smoked render a state of sedate euphoria for 1 hour. During that time, the user is alert, but calm and unbothered. Gain immunity to Fear and cannot use any Active Martial skills for the duration. This drug is only mildly addictive and should be roleplayed as such.",
    "fee_silver": 0,
    "qty_produced": 0,
    "reagent_1": "Distilled Spirits",
    "reagent_1_qty": 2,
    "reagent_1_rarity": "Uncommon",
    "reagent_2": "Harrowdust",
    "reagent_2_qty": 2,
    "reagent_2_rarity": "Uncommon",
    "reagent_3": "Widow's Petal",
    "reagent_3_qty": 1,
    "reagent_3_rarity": "Uncommon",
    "reagent_4": "Wraith Orchid",
    "reagent_4_qty": 1,
    "reagent_4_rarity": "Common",
    "reagent_5": "Merchant's Leaf",
    "value_copper": 67,
    "value_silver": 6,
    "value_gold": 0,
}

WINGS_OF_CORVUS = {
    "typeclass": "typeclasses.objects.ConsumableObject",
    "key": "Wings of Corvus",
    "aliases": ["wings of corvus"],
    "craft_source": "apothecary",
    "substance_type": "drug",
    "level": 2,
    "effect": "A specific mixture of dried leaves and seeds that when chewed or smoked, renders a state tranquilizing euphoria accompanied by mild hallucinations. Gain 1 temporary level of Perception, 1 temporary use of Tough, the Weakness effect, and Academics reduced to 0 for 1 hour. Does not stack with itself or other consumables that grant Perception and/or Tough. This drug is highly addictive and should be roleplayed as such.",
    "fee_silver": 0,
    "qty_produced": 0,
    "reagent_1": "Distilled Spirits",
    "reagent_1_qty": 3,
    "reagent_1_rarity": "Uncommon",
    "reagent_2": "Tarkathi Poppy",
    "reagent_2_qty": 1,
    "reagent_2_rarity": "Uncommon",
    "reagent_3": "Blood Medallion",
    "reagent_3_qty": 1,
    "reagent_3_rarity": "Uncommon",
    "reagent_4": "Red Lotus",
    "reagent_4_qty": 1,
    "reagent_4_rarity": "Common",
    "reagent_5": "Verbaena",
    "value_copper": 67,
    "value_silver": 6,
    "value_gold": 0,
}

# ==== Level 3 Apotheca ====

GRIZZLYS_DECOCTION = {
    "typeclass": "typeclasses.objects.ConsumableObject",
    "key": "Grizzly's Decoction",
    "aliases": ["grizzly's decoction"],
    "craft_source": "apothecary",
    "substance_type": "apotheca",
    "level": 3,
    "effect": "Add 3 temporary points of Tough to total Armor Value. Must be used before any purchased levels of Tough. This potion’s effects are canceled the next time the player uses all three temporary Tough points or the event ends. Does not stack with itself or other consumables that grant Tough.",
    "fee_silver": 3,
    "qty_produced": 3,
    "reagent_1": "Distilled Spirits",
    "reagent_1_qty": 2,
    "reagent_1_rarity": "Common",
    "reagent_2": "Verbaena",
    "reagent_2_qty": 1,
    "reagent_2_rarity": "Loot Drop",
    "reagent_3": "Spirit Essence",
    "reagent_3_qty": 1,
    "reagent_3_rarity": "Uncommon",
    "reagent_4": "Ergot Seeds",
    "reagent_4_qty": 1,
    "reagent_4_rarity": "Uncommon",
    "reagent_5": "Wintercrown",
    "value_copper": 149,
    "value_silver": 14,
    "value_gold": 1,
}

SERUM_OF_THE_LAST_TOWER = {
    "typeclass": "typeclasses.objects.ConsumableObject",
    "key": "Serum of the Last Tower",
    "aliases": ["serum of the last tower"],
    "craft_source": "apothecary",
    "substance_type": "apotheca",
    "level": 3,
    "effect": "Gain 2 temporary uses of Resist. Must be used before any purchased levels of Resist. This potion’s effects are canceled the next time the player uses both Resists or the event ends. Does not stack with itself or other consumables that grant Resist.",
    "fee_silver": 2,
    "qty_produced": 2,
    "reagent_1": "Distilled Spirits",
    "reagent_1_qty": 3,
    "reagent_1_rarity": "Rare",
    "reagent_2": "Waste Lilly",
    "reagent_2_qty": 2,
    "reagent_2_rarity": "Uncommon",
    "reagent_3": "Duskland Rose",
    "reagent_3_qty": 3,
    "reagent_3_rarity": "Common",
    "reagent_4": "Black Salt",
    "reagent_4_qty": 2,
    "reagent_4_rarity": "Rare",
    "reagent_5": "Embercap",
    "value_copper": 155,
    "value_silver": 15,
    "value_gold": 1,
}

BRINK = {
    "typeclass": "typeclasses.objects.ConsumableObject",
    "key": "Brink",
    "aliases": ["brink"],
    "craft_source": "apothecary",
    "substance_type": "apotheca",
    "level": 3,
    "effect": "Add 180 seconds to Bleeding Count. May only be used while in the Bleeding Count. Does not stack with itself or other consumables that grant seconds to the Bleeding Count.",
    "fee_silver": 3,
    "qty_produced": 3,
    "reagent_1": "Distilled Spirits",
    "reagent_1_qty": 3,
    "reagent_1_rarity": "Uncommon",
    "reagent_2": "Ergot Seeds",
    "reagent_2_qty": 4,
    "reagent_2_rarity": "Common",
    "reagent_3": "Merchant's Leaf",
    "reagent_3_qty": 2,
    "reagent_3_rarity": "Uncommon",
    "reagent_4": "Thornwood Fern",
    "reagent_4_qty": 3,
    "reagent_4_rarity": "Rare",
    "reagent_5": "Waste Lilly",
    "value_copper": 169,
    "value_silver": 16,
    "value_gold": 1,
}

REAPERS_ELIXIR = {
    "typeclass": "typeclasses.objects.ConsumableObject",
    "key": "Reaper's Elixir",
    "aliases": ["reaper's elixir"],
    "craft_source": "apothecary",
    "substance_type": "apotheca",
    "level": 3,
    "effect": "Immediately stop the Dying Count. Cannot be administered by yourself, it must be administered by someone else. May only be used while in the Dying Count. All Death & Dying rules apply after stopping the Dying Count (i.e. you enter the Wounded State).",
    "fee_silver": 6,
    "qty_produced": 6,
    "reagent_1": "Distilled Spirits",
    "reagent_1_qty": 2,
    "reagent_1_rarity": "Rare",
    "reagent_2": "Grave Blood",
    "reagent_2_qty": 1,
    "reagent_2_rarity": "Common",
    "reagent_3": "Hollyrue",
    "reagent_3_qty": 1,
    "reagent_3_rarity": "Uncommon",
    "reagent_4": "Wraith Orchid",
    "reagent_4_qty": 1,
    "reagent_4_rarity": "Loot Drop",
    "reagent_5": "Vampire Blood",
    "value_copper": 193,
    "value_silver": 19,
    "value_gold": 1,
}

AWAKENERS_DRAUGHT = {
    "typeclass": "typeclasses.objects.ConsumableObject",
    "key": "Awakener's Draught",
    "aliases": ["awakener's draught"],
    "craft_source": "apothecary",
    "substance_type": "apotheca",
    "level": 3,
    "effect": "The antidote to The Sleeper poison.",
    "fee_silver": 5,
    "qty_produced": 5,
    "reagent_1": "Distilled Spirits",
    "reagent_1_qty": 2,
    "reagent_1_rarity": "Rare",
    "reagent_2": "Embercap",
    "reagent_2_qty": 4,
    "reagent_2_rarity": "Common",
    "reagent_3": "Celandine",
    "reagent_3_qty": 3,
    "reagent_3_rarity": "Common",
    "reagent_4": "Merchant's Leaf",
    "reagent_4_qty": 3,
    "reagent_4_rarity": "Uncommon",
    "reagent_5": "Harrowdust",
    "value_copper": 154,
    "value_silver": 15,
    "value_gold": 1,
}

STYPTIC_TONIC = {
    "typeclass": "typeclasses.objects.ConsumableObject",
    "key": "Styptic Tonic",
    "aliases": ["styptic tonic"],
    "craft_source": "apothecary",
    "substance_type": "apotheca",
    "level": 3,
    "effect": "The antidote to the Leech poison.",
    "fee_silver": 6,
    "qty_produced": 6,
    "reagent_1": "Distilled Spirits",
    "reagent_1_qty": 3,
    "reagent_1_rarity": "Rare",
    "reagent_2": "Lachrymite Resin",
    "reagent_2_qty": 1,
    "reagent_2_rarity": "Common",
    "reagent_3": "Black Salt",
    "reagent_3_qty": 2,
    "reagent_3_rarity": "Uncommon",
    "reagent_4": "Blood Medallion",
    "reagent_4_qty": 4,
    "reagent_4_rarity": "Uncommon",
    "reagent_5": "Thornwood Fern",
    "value_copper": 150,
    "value_silver": 15,
    "value_gold": 1,
}

TINCTURE_OF_THE_WHITE_VEIN = {
    "typeclass": "typeclasses.objects.ConsumableObject",
    "key": "Tincture of the White Vein",
    "aliases": ["tincture of the white vein"],
    "craft_source": "apothecary",
    "substance_type": "apotheca",
    "level": 3,
    "effect": "Immediately cure the Twitch disease. As the victims are often hydrophobic, the cure must be administered through the blood.",
    "fee_silver": 5,
    "qty_produced": 5,
    "reagent_1": "Distilled Spirits",
    "reagent_1_qty": 1,
    "reagent_1_rarity": "Rare",
    "reagent_2": "Grave Blood",
    "reagent_2_qty": 3,
    "reagent_2_rarity": "Rare",
    "reagent_3": "Hag's Wort",
    "reagent_3_qty": 3,
    "reagent_3_rarity": "Common",
    "reagent_4": "Willow Root",
    "reagent_4_qty": 3,
    "reagent_4_rarity": "Uncommon",
    "reagent_5": "Crypt Moss",
    "value_copper": 150,
    "value_silver": 15,
    "value_gold": 1,
}

GERMAINES_CURE = {
    "typeclass": "typeclasses.objects.ConsumableObject",
    "key": "Germaine's Cure",
    "aliases": ["germaine's cure"],
    "craft_source": "apothecary",
    "substance_type": "apotheca",
    "level": 3,
    "effect": "Immediately cure the Red Plague disease.",
    "fee_silver": 4,
    "qty_produced": 4,
    "reagent_1": "Distilled Spirits",
    "reagent_1_qty": 2,
    "reagent_1_rarity": "Rare",
    "reagent_2": "Lachrymite Resin",
    "reagent_2_qty": 3,
    "reagent_2_rarity": "Common",
    "reagent_3": "Luminesce",
    "reagent_3_qty": 3,
    "reagent_3_rarity": "Uncommon",
    "reagent_4": "Amber Lichen",
    "reagent_4_qty": 2,
    "reagent_4_rarity": "Rare",
    "reagent_5": "Embercap",
    "value_copper": 150,
    "value_silver": 15,
    "value_gold": 1,
}

WEAPONMASTERS_DECOCTION = {
    "typeclass": "typeclasses.objects.ConsumableObject",
    "key": "Weaponmaster's Decoction",
    "aliases": ["weaponmaster's decoction"],
    "craft_source": "apothecary",
    "substance_type": "apotheca",
    "level": 3,
    "effect": "Gain 3 uses of any Active Martial skill, even ones you don't have access to, excluding Resist. Cleaves used with this potion can be used with one-handed weapons. Stuns used with this potion do not require an attack from behind.",
    "fee_silver": 5,
    "qty_produced": 5,
    "reagent_1": "Distilled Spirits",
    "reagent_1_qty": 3,
    "reagent_1_rarity": "Rare",
    "reagent_2": "Entheric Oil",
    "reagent_2_qty": 4,
    "reagent_2_rarity": "Common",
    "reagent_3": "Sayge",
    "reagent_3_qty": 2,
    "reagent_3_rarity": "Uncommon",
    "reagent_4": "Duskland Rose",
    "reagent_4_qty": 2,
    "reagent_4_rarity": "Uncommon",
    "reagent_5": "Duskland Rose",
    "value_copper": 150,
    "value_silver": 15,
    "value_gold": 1,
}

BREATH_OF_MEDEINA = {
    "typeclass": "typeclasses.objects.ConsumableObject",
    "key": "Breath of Medeina",
    "aliases": ["breath of medeina"],
    "craft_source": "apothecary",
    "substance_type": "apotheca",
    "level": 3,
    "effect": "Antidote to the Lirit’s Kiss poison.",
    "fee_silver": 5,
    "qty_produced": 5,
    "reagent_1": "Distilled Spirits",
    "reagent_1_qty": 2,
    "reagent_1_rarity": "Rare",
    "reagent_2": "Grave Blood",
    "reagent_2_qty": 3,
    "reagent_2_rarity": "Rare",
    "reagent_3": "Entheric Oil",
    "reagent_3_qty": 4,
    "reagent_3_rarity": "Uncommon",
    "reagent_4": "Crypt Moss",
    "reagent_4_qty": 3,
    "reagent_4_rarity": "Common",
    "reagent_5": "Phosphorous",
    "value_copper": 178,
    "value_silver": 17,
    "value_gold": 1,
}

SILENCE_OF_THE_SERPENT = {
    "typeclass": "typeclasses.objects.ConsumableObject",
    "key": "Silence of the Serpent",
    "aliases": ["silence of the serpent"],
    "craft_source": "apothecary",
    "substance_type": "apotheca",
    "level": 3,
    "effect": "Antidote to the Song of the Asp poison.",
    "fee_silver": 5,
    "qty_produced": 5,
    "reagent_1": "Distilled Spirits",
    "reagent_1_qty": 3,
    "reagent_1_rarity": "Rare",
    "reagent_2": "Hag's Wort",
    "reagent_2_qty": 3,
    "reagent_2_rarity": "Rare",
    "reagent_3": "Embercap",
    "reagent_3_qty": 2,
    "reagent_3_rarity": "Uncommon",
    "reagent_4": "Red Lotus",
    "reagent_4_qty": 2,
    "reagent_4_rarity": "Common",
    "reagent_5": "Celandine",
    "value_copper": 161,
    "value_silver": 16,
    "value_gold": 1,
}

# ==== Level 3 Poison ====

THE_SLEEPER = {
    "typeclass": "typeclasses.objects.ConsumableObject",
    "key": "The Sleeper",
    "aliases": ["the sleeper"],
    "craft_source": "apothecary",
    "substance_type": "poison",
    "level": 3,
    "effect": "The target is afflicted by a drunken state and experiences weakness. When the afflicted next goes to sleep, they will enter their dying count and quietly expire in their sleep after their dying count is up.",
    "fee_silver": 4,
    "qty_produced": 4,
    "reagent_1": "Distilled Spirits",
    "reagent_1_qty": 4,
    "reagent_1_rarity": "Uncommon",
    "reagent_2": "Tarkathi Poppy",
    "reagent_2_qty": 2,
    "reagent_2_rarity": "Common",
    "reagent_3": "Luminesce",
    "reagent_3_qty": 1,
    "reagent_3_rarity": "Rare",
    "reagent_4": "Death's Head Cap",
    "reagent_4_qty": 3,
    "reagent_4_rarity": "Rare",
    "reagent_5": "Black Lotus",
    "value_copper": 157,
    "value_silver": 15,
    "value_gold": 1,
}

LEECH = {
    "typeclass": "typeclasses.objects.ConsumableObject",
    "key": "Leech",
    "aliases": ["leech"],
    "craft_source": "apothecary",
    "substance_type": "poison",
    "level": 3,
    "effect": "In 15 minutes, causes bleeding from orifices. In 30 minutes, causes bleeding from all pores. In 45 minutes, enter Dying Count.",
    "fee_silver": 2,
    "qty_produced": 2,
    "reagent_1": "Distilled Spirits",
    "reagent_1_qty": 3,
    "reagent_1_rarity": "Rare",
    "reagent_2": "Death's Head Cap",
    "reagent_2_qty": 1,
    "reagent_2_rarity": "Loot Drop",
    "reagent_3": "Ghoul Venom",
    "reagent_3_qty": 2,
    "reagent_3_rarity": "Rare",
    "reagent_4": "Fulger Powder",
    "reagent_4_qty": 2,
    "reagent_4_rarity": "Uncommon",
    "reagent_5": "Creeper Moss",
    "value_copper": 181,
    "value_silver": 18,
    "value_gold": 1,
}

REST_DENIED = {
    "typeclass": "typeclasses.objects.ConsumableObject",
    "key": "Rest Denied",
    "aliases": ["rest denied"],
    "craft_source": "apothecary",
    "substance_type": "poison",
    "level": 3,
    "effect": "Target cannot be embraced by Lirit if they die while under the effects of this poison.",
    "fee_silver": 4,
    "qty_produced": 4,
    "reagent_1": "Distilled Spirits",
    "reagent_1_qty": 1,
    "reagent_1_rarity": "Loot Drop",
    "reagent_2": "Essence of the Unhallowed",
    "reagent_2_qty": 1,
    "reagent_2_rarity": "Loot Drop",
    "reagent_3": "Ghoul Venom",
    "reagent_3_qty": 1,
    "reagent_3_rarity": "Rare",
    "reagent_4": "Fulger Powder",
    "reagent_4_qty": 1,
    "reagent_4_rarity": "Uncommon",
    "reagent_5": "Creeper Moss",
    "value_copper": 177,
    "value_silver": 17,
    "value_gold": 1,
}

LIRITS_KISS = {
    "typeclass": "typeclasses.objects.ConsumableObject",
    "key": "Lirit's Kiss",
    "aliases": ["lirit's kiss"],
    "craft_source": "apothecary",
    "substance_type": "poison",
    "level": 3,
    "effect": "Target suffers immediate unconsciousness and begins spitting blood. Immediately enter Dying Count, with Dying Count reduced to 1 minute.",
    "fee_silver": 6,
    "qty_produced": 6,
    "reagent_1": "Distilled Spirits",
    "reagent_1_qty": 3,
    "reagent_1_rarity": "Uncommon",
    "reagent_2": "Crypt Moss",
    "reagent_2_qty": 4,
    "reagent_2_rarity": "Black Market",
    "reagent_3": "Basilisk Venom",
    "reagent_3_qty": 2,
    "reagent_3_rarity": "Rare",
    "reagent_4": "Fulger Powder",
    "reagent_4_qty": 3,
    "reagent_4_rarity": "Uncommon",
    "reagent_5": "Wraith Orchid",
    "value_copper": 198,
    "value_silver": 19,
    "value_gold": 1,
}

SONG_OF_THE_ASP = {
    "typeclass": "typeclasses.objects.ConsumableObject",
    "key": "Song of the Asp",
    "aliases": ["song of the asp"],
    "craft_source": "apothecary",
    "substance_type": "poison",
    "level": 3,
    "effect": "Target suffers uncurable Weakness and deliriousness. Magisters of reported victims complaining of incessant singing that couldn't be heard by anyone else, among other hallucinations. Death occurs in 12 hours or the end of the event in which the poison was administered, whichever is sooner.",
    "fee_silver": 5,
    "qty_produced": 5,
    "reagent_1": "Distilled Spirits",
    "reagent_1_qty": 3,
    "reagent_1_rarity": "Uncommon",
    "reagent_2": "Red Lotus",
    "reagent_2_qty": 3,
    "reagent_2_rarity": "Black Market",
    "reagent_3": "Asp Venom",
    "reagent_3_qty": 2,
    "reagent_3_rarity": "Uncommon",
    "reagent_4": "Wraith Orchid",
    "reagent_4_qty": 2,
    "reagent_4_rarity": "Rare",
    "reagent_5": "Death's Head Cap",
    "value_copper": 167,
    "value_silver": 16,
    "value_gold": 1,
}

# ==== Level 3 Drug ====

RESET = {
    "typeclass": "typeclasses.objects.ConsumableObject",
    "key": "Reset",
    "aliases": ["reset"],
    "craft_source": "apothecary",
    "substance_type": "drug",
    "level": 3,
    "effect": "Extremely euphoric, addictive drug that causes short term happiness but permanent memory loss. Gain 2 Tough for 1 hour. First use of the drug, lose a memory of your choice. Each use after, lose a memory of your choice AND a # of rolls from the Memory Loss Table equal to the # of times you have taken the drug after the first. Your mind forgets the memories, but any trauma caused by past experiences is still felt by your body (i.e., you may experience anxiety or tenseness when confronted with something that would otherwise remind you of the lost memory).",
    "fee_silver": 3,
    "qty_produced": 3,
    "reagent_1": "Distilled Spirits",
    "reagent_1_qty": 3,
    "reagent_1_rarity": "Rare",
    "reagent_2": "Black Lotus",
    "reagent_2_qty": 3,
    "reagent_2_rarity": "Uncommon",
    "reagent_3": "Red Lotus",
    "reagent_3_qty": 2,
    "reagent_3_rarity": "Uncommon",
    "reagent_4": "Blood Medallion",
    "reagent_4_qty": 1,
    "reagent_4_rarity": "Common",
    "reagent_5": "Hollyrue",
    "value_copper": 125,
    "value_silver": 12,
    "value_gold": 1,
}

STONEFACE = {
    "typeclass": "typeclasses.objects.ConsumableObject",
    "key": "Stoneface",
    "aliases": ["stoneface"],
    "craft_source": "apothecary",
    "substance_type": "drug",
    "level": 3,
    "effect": "Immune to Fear and emotional doubts. Cannot benefit from inspired abilities while under the effect of the drug (such as Rousing Speech, Aurorym ceremonies, etc), including those gained before the drug was consumed. Must act without emotion, including emotion towards self preservation and safety of others. Lasts for 2 hours.",
    "fee_silver": 0,
    "qty_produced": 0,
    "reagent_1": "Distilled Spirits",
    "reagent_1_qty": 3,
    "reagent_1_rarity": "Rare",
    "reagent_2": "Waste Lilly",
    "reagent_2_qty": 2,
    "reagent_2_rarity": "Uncommon",
    "reagent_3": "Amber Lichen",
    "reagent_3_qty": 1,
    "reagent_3_rarity": "Uncommon",
    "reagent_4": "Creeper Moss",
    "reagent_4_qty": 3,
    "reagent_4_rarity": "Common",
    "reagent_5": "Luminesce",
    "value_copper": 126,
    "value_silver": 12,
    "value_gold": 1,
}

ELIXIR_OF_REVELATION = {
    "typeclass": "typeclasses.objects.ConsumableObject",
    "key": "Elixir of Revelation",
    "aliases": ["elixir of revelation"],
    "craft_source": "apothecary",
    "substance_type": "drug",
    "level": 3,
    "effect": "An intense hallucinogenic. The user must have at least Academics 2 to gain the following benefit: May ignore ALL lore requirements to open and read lores for 10 minutes. Forbidden Lores still require the Forbidden Lore skill. Cannot use those lores to level up if they do not meet the standard requirement yet; but they can hold on to the lores and use them later when they do. Roll for a madness on the Forbidden Lore Madness table each time you use this drug. Academics reduced to 0 for 1 hour afterwards.",
    "fee_silver": 4,
    "qty_produced": 4,
    "reagent_1": "Distilled Spirits",
    "reagent_1_qty": 3,
    "reagent_1_rarity": "Rare",
    "reagent_2": "Hag's Wort",
    "reagent_2_qty": 2,
    "reagent_2_rarity": "Rare",
    "reagent_3": "Black Lotus",
    "reagent_3_qty": 1,
    "reagent_3_rarity": "Uncommon",
    "reagent_4": "Harrowdust",
    "reagent_4_qty": 2,
    "reagent_4_rarity": "Common",
    "reagent_5": "Gold Lotus",
    "value_copper": 131,
    "value_silver": 13,
    "value_gold": 1,
}
