"""
AI dialogue commands — `ask`, `farewell`, and a `whisper` override.

Players can converse with NPCs that have an `ai_personality` attribute.
The reply is generated by an LLM (see world/ai_npc.py).

The whisper override keeps the stock behavior for player-to-player
whispers but routes whispers at AI NPCs through the LLM — so the
sidebar UI's "Whisper" action still works on these NPCs.
"""
from evennia import Command
from evennia.commands.default.general import CmdWhisper as _DefaultCmdWhisper
from evennia.commands.default.general import CmdSay as _DefaultCmdSay


class CmdAsk(Command):
    """
    Speak to an NPC.

    Usage:
      ask <npc> <message>
      ask <npc> = <message>

    Examples:
      ask crane about the writ
      ask soap why the hat
      ask mae = where is your sister

    The NPC will reply in-character. Conversation history is remembered
    while you stay in the same room.
    """
    key = "ask"
    locks = "cmd:all()"
    help_category = "Social"

    def func(self):
        caller = self.caller
        args = (self.args or "").strip()
        if not args:
            caller.msg("Ask whom about what?\n  Usage: |wask <npc> <message>|n")
            return

        # Parse: "ask <npc> = <message>" OR "ask <npc> <message>"
        if "=" in args:
            target_name, _, message = args.partition("=")
        else:
            parts = args.split(None, 1)
            if len(parts) < 2:
                caller.msg("What do you want to ask them?")
                return
            target_name, message = parts
        target_name = target_name.strip().lstrip("@")
        message = message.strip().rstrip("?.!, ")
        if not target_name or not message:
            caller.msg("Usage: |wask <npc> <message>|n")
            return

        target = caller.search(target_name, location=caller.location)
        if not target:
            return
        if not target.attributes.get("ai_personality", default=None):
            caller.msg(
                f"|x{target.key} gives you a blank look and says nothing.|n"
            )
            return

        from world import ai_npc

        def _on_reply(reply):
            if not reply:
                reply = "..."
            # Broadcast to the room so other players see the exchange too.
            if caller.location:
                caller.location.msg_contents(
                    f'|c{target.key}|n says, "{reply}"'
                )
            else:
                caller.msg(f'|c{target.key}|n says, "{reply}"')

        # Announce the question so the room sees it too.
        if caller.location:
            caller.location.msg_contents(
                f'|g{caller.key}|n asks |c{target.key}|n, "{message}"'
            )
        caller.msg(f"|x({target.key} considers your words...)|n")
        ai_npc.chat(target, caller, message, _on_reply)


class CmdWhisper(_DefaultCmdWhisper):
    """
    Whisper privately to someone.

    Usage:
      whisper <target> = <message>
      whisper <target> <message>

    Whispering to an NPC who can speak (has an AI personality) routes
    the message to them as a private conversation — the NPC replies
    only to you, not the room.
    """
    key = "whisper"

    def func(self):
        caller = self.caller
        args = (self.args or "").strip()
        if not args:
            return super().func()

        # Parse target + message same way the default command does.
        if "=" in args:
            target_name, _, message = args.partition("=")
        else:
            parts = args.split(None, 1)
            if len(parts) < 2:
                return super().func()
            target_name, message = parts
        target_name = target_name.strip()
        message = message.strip()
        if not target_name or not message:
            return super().func()

        # Try to find a local target first (NPC in same room).
        target = caller.search(target_name, location=caller.location, quiet=True)
        if isinstance(target, list):
            target = target[0] if target else None
        if target and target.attributes.get("ai_personality", default=None):
            from world import ai_npc

            def _on_reply(reply):
                if not reply:
                    reply = "..."
                caller.msg(
                    f'|c{target.key}|n whispers to you, "{reply}"'
                )

            caller.msg(f"|gYou whisper to {target.key}, \"{message}\"|n")
            caller.msg(f"|x({target.key} leans in to listen...)|n")
            ai_npc.chat(target, caller, message, _on_reply)
            return

        # Not an AI NPC — hand off to default whisper behavior.
        return super().func()


class CmdSay(_DefaultCmdSay):
    """
    Speak aloud to everyone in the room.

    Usage:
      say <message>
      "<message>      (shortcut)

    Everyone in the room hears you. If your message names an AI NPC
    in the room, that NPC will respond — addressing them directly is
    the natural way to start a conversation with them.

    For a private one-on-one with an NPC, use:
      ask <npc> <question>      — direct question
      whisper <npc>=<message>   — private speech
    """
    key = "say"

    def func(self):
        # Run the default say first so the room hears the speech.
        super().func()
        # Then check whether any AI NPC in the room was addressed by
        # name. If so, route the message through the LLM to that NPC.
        message = (self.args or "").strip().lstrip(":'\"").strip()
        if not message:
            return
        location = self.caller.location
        if not location:
            return
        addressed = []
        msg_lower = message.lower()
        for obj in location.contents:
            if obj == self.caller:
                continue
            if not obj.attributes.get("ai_personality", default=None):
                continue
            # Match the NPC's key OR any of their aliases against
            # whole words in the message. "hegga" matches "Hegga,"
            # but not "Heggard" or "agghegg".
            candidates = [obj.key.lower()]
            try:
                candidates.extend(a.lower() for a in obj.aliases.all())
            except Exception:
                pass
            for cand in candidates:
                if not cand:
                    continue
                # Word-boundary check: the candidate appears in msg
                # surrounded by spaces, punctuation, or string edges.
                import re
                pattern = r"\b" + re.escape(cand) + r"\b"
                if re.search(pattern, msg_lower):
                    addressed.append(obj)
                    break
        if not addressed:
            return
        # Route the message to the first matched NPC (avoid spamming
        # multiple NPCs from a single say). Subsequent NPCs would need
        # their own ask / direct address.
        target = addressed[0]
        from world import ai_npc

        def _on_reply(reply):
            if not reply:
                reply = "..."
            location.msg_contents(
                f'|c{target.key}|n says, "{reply}"'
            )

        location.msg_contents(
            f"|x({target.key} considers your words...)|n",
            from_obj=self.caller,
        )
        ai_npc.chat(target, self.caller, message, _on_reply)


class CmdFarewell(Command):
    """
    End a conversation. The NPC forgets what you discussed.

    Usage:
      farewell <npc>

    Useful if you want the NPC to start a fresh conversation next time,
    or if the history has become cluttered.
    """
    key = "farewell"
    aliases = ["bye"]
    locks = "cmd:all()"
    help_category = "Social"

    def func(self):
        caller = self.caller
        target_name = (self.args or "").strip()
        if not target_name:
            caller.msg("Say farewell to whom?")
            return
        target = caller.search(target_name, location=caller.location)
        if not target:
            return
        if not target.attributes.get("ai_personality", default=None):
            caller.msg(f"{target.key} has nothing to say anyway.")
            return
        from world import ai_npc
        ai_npc.reset_history(target, caller)
        if caller.location:
            caller.location.msg_contents(
                f"|g{caller.key}|n bids |c{target.key}|n farewell."
            )
