"""
AI dialogue commands — `ask` and `talk`.

Players can converse with NPCs that have an `ai_personality` attribute.
The reply is generated by an LLM (see world/ai_npc.py).
"""
from evennia import Command


class CmdAsk(Command):
    """
    Speak to an NPC.

    Usage:
      ask <npc> <message>
      ask <npc> = <message>

    Examples:
      ask crane about the writ
      ask soap why the hat
      ask mae = where is your sister

    The NPC will reply in-character. Conversation history is remembered
    while you stay in the same room.
    """
    key = "ask"
    locks = "cmd:all()"
    help_category = "Social"

    def func(self):
        caller = self.caller
        args = (self.args or "").strip()
        if not args:
            caller.msg("Ask whom about what?\n  Usage: |wask <npc> <message>|n")
            return

        # Parse: "ask <npc> = <message>" OR "ask <npc> <message>"
        if "=" in args:
            target_name, _, message = args.partition("=")
        else:
            parts = args.split(None, 1)
            if len(parts) < 2:
                caller.msg("What do you want to ask them?")
                return
            target_name, message = parts
        target_name = target_name.strip().lstrip("@")
        message = message.strip().rstrip("?.!, ")
        if not target_name or not message:
            caller.msg("Usage: |wask <npc> <message>|n")
            return

        target = caller.search(target_name, location=caller.location)
        if not target:
            return
        if not target.attributes.get("ai_personality", default=None):
            caller.msg(
                f"|x{target.key} gives you a blank look and says nothing.|n"
            )
            return

        from world import ai_npc

        def _on_reply(reply):
            if not reply:
                reply = "..."
            # Broadcast to the room so other players see the exchange too.
            if caller.location:
                caller.location.msg_contents(
                    f'|c{target.key}|n says, "{reply}"'
                )
            else:
                caller.msg(f'|c{target.key}|n says, "{reply}"')

        # Announce the question so the room sees it too.
        if caller.location:
            caller.location.msg_contents(
                f'|g{caller.key}|n asks |c{target.key}|n, "{message}"'
            )
        caller.msg(f"|x({target.key} considers your words...)|n")
        ai_npc.chat(target, caller, message, _on_reply)


class CmdFarewell(Command):
    """
    End a conversation. The NPC forgets what you discussed.

    Usage:
      farewell <npc>

    Useful if you want the NPC to start a fresh conversation next time,
    or if the history has become cluttered.
    """
    key = "farewell"
    aliases = ["bye"]
    locks = "cmd:all()"
    help_category = "Social"

    def func(self):
        caller = self.caller
        target_name = (self.args or "").strip()
        if not target_name:
            caller.msg("Say farewell to whom?")
            return
        target = caller.search(target_name, location=caller.location)
        if not target:
            return
        if not target.attributes.get("ai_personality", default=None):
            caller.msg(f"{target.key} has nothing to say anyway.")
            return
        from world import ai_npc
        ai_npc.reset_history(target, caller)
        if caller.location:
            caller.location.msg_contents(
                f"|g{caller.key}|n bids |c{target.key}|n farewell."
            )
