"""
AI dialogue commands — `ask`, `farewell`, and a `whisper` override.

Players can converse with NPCs that have an `ai_personality` attribute.
The reply is generated by an LLM (see world/ai_npc.py).

The whisper override keeps the stock behavior for player-to-player
whispers but routes whispers at AI NPCs through the LLM — so the
sidebar UI's "Whisper" action still works on these NPCs.
"""
from evennia import Command
from evennia.commands.default.general import CmdWhisper as _DefaultCmdWhisper
from evennia.commands.default.general import CmdSay as _DefaultCmdSay


def _fire_npc_dialogue(caller, target, question, reply, channel="ask"):
    """Emit an `npc_dialogue` OOB event to the caller's web-client
    sessions so the frontend can render a dialogue modal with topic
    chips. Additive — the chat stream is unchanged for backward compat
    and for bystanders in the room.

    channel = "ask" | "whisper" | "say" so the modal can distinguish
    public vs private conversations.
    """
    try:
        topics_raw = target.attributes.get("ai_quest_topics", default=None)
        if not topics_raw:
            # Fall back to quest-hook summaries if explicit topics missing
            hooks = target.attributes.get("ai_quest_hooks", default=None) or []
            topics_raw = [h[:40].strip() for h in hooks[:4]]
        topics = [t for t in (topics_raw or []) if t]
        import time as _time
        payload = {
            "type": "npc_dialogue",
            "_ts": _time.time(),
            "channel": channel,
            "npc": target.key,
            "npcDbref": getattr(target, "dbref", ""),
            "npcDesc": (target.db.desc or "")[:240],
            "question": question,
            "reply": reply,
            "topics": topics,
        }
        for sess in caller.sessions.all():
            if (getattr(sess, "protocol_key", "") or "").startswith("webclient"):
                sess.msg(event=payload)
    except Exception:
        pass


def _parse_target_and_message(caller, args):
    """Parse '<target> <message>' or '<target> = <message>' where target
    may be a multi-word NPC name like 'Mab the Gambler'.

    Uses '=' as a reliable delimiter if present. Otherwise tries
    progressively longer prefixes as the target name, searching in
    the caller's room, and treats whatever remains as the message.

    Returns (target_obj, message_str) — either may be None on failure.
    """
    args = args.strip()

    # ── Explicit delimiter ──────────────────────────────────────────
    if "=" in args:
        target_name, _, message = args.partition("=")
        target_name = target_name.strip().lstrip("@")
        message = message.strip().rstrip("?.!, ")
        target = caller.search(target_name, location=caller.location)
        return target, message

    # ── Strip filler word "about" ───────────────────────────────────
    # "ask mab the gambler about gossip" → "ask mab the gambler gossip"
    # Don't strip if "about" IS the entire message.
    cleaned = args
    parts_check = args.rsplit(" about ", 1)
    if len(parts_check) == 2 and parts_check[1].strip():
        cleaned = parts_check[0] + " " + parts_check[1]

    # ── Progressive match: try longest target name first ────────────
    words = cleaned.split()
    if len(words) < 2:
        # Just a name, no message
        target = caller.search(cleaned.strip(), location=caller.location, quiet=True)
        if isinstance(target, list):
            target = target[0] if target else None
        return target, ""

    # Try from longest possible target (all-but-last word) down to
    # shortest (first word only). First successful search wins.
    for split_at in range(len(words) - 1, 0, -1):
        candidate = " ".join(words[:split_at]).strip().lstrip("@")
        remainder = " ".join(words[split_at:]).strip().rstrip("?.!, ")
        result = caller.search(candidate, location=caller.location, quiet=True)
        if isinstance(result, list):
            result = result[0] if result else None
        if result:
            return result, remainder

    # Fallback: treat first word as name (may fail), rest as message.
    target_name = words[0].strip().lstrip("@")
    message = " ".join(words[1:]).strip().rstrip("?.!, ")
    target = caller.search(target_name, location=caller.location)
    return target, message


class CmdAsk(Command):
    """
    Speak to an NPC.

    Usage:
      ask <npc> <message>
      ask <npc> = <message>

    Examples:
      ask crane about the writ
      ask soap why the hat
      ask mae = where is your sister

    The NPC will reply in-character. Conversation history is remembered
    while you stay in the same room.
    """
    key = "ask"
    locks = "cmd:all()"
    help_category = "Social"

    def func(self):
        caller = self.caller
        args = (self.args or "").strip()
        if not args:
            caller.msg("Ask whom about what?\n  Usage: |wask <npc> <message>|n")
            return

        target, message = _parse_target_and_message(caller, args)
        if not target:
            return
        if not message:
            caller.msg("What do you want to ask them?")
            return
        if not target.attributes.get("ai_personality", default=None):
            caller.msg(
                f"|x{target.key} gives you a blank look and says nothing.|n"
            )
            return

        from world import ai_npc
        from world.npc_gifts import process_gift_markers

        def _on_reply(reply):
            if not reply:
                reply = "..."
            reply = process_gift_markers(reply, target, caller)
            if not reply:
                reply = "..."
            # Broadcast to the room so other players see the exchange too.
            if caller.location:
                caller.location.msg_contents(
                    f'|c{target.key}|n says, "{reply}"'
                )
            else:
                caller.msg(f'|c{target.key}|n says, "{reply}"')
            # Rich OOB dialogue event — web client shows a modal with
            # the reply + the NPC's available topics. Telnet clients
            # already have the chat line above; OOB is additive.
            _fire_npc_dialogue(caller, target, message, reply)
            # Engaging an NPC in conversation surfaces any quest offers
            # they hold. The QuestOfferModal pops in addition to the
            # dialogue panel — quest-giver NPCs (the Herald, Ringmaster,
            # etc.) put their work in front of the player at the moment
            # the player chooses to engage rather than the moment they
            # walk into the room.
            try:
                from world.quest_offers import push_quest_offers_for_npc
                push_quest_offers_for_npc(caller, target)
            except Exception:
                pass

        # Announce the question so the room sees it too.
        if caller.location:
            caller.location.msg_contents(
                f'|g{caller.key}|n asks |c{target.key}|n, "{message}"'
            )
        caller.msg(f"|x({target.key} considers your words...)|n")
        ai_npc.chat(target, caller, message, _on_reply)


class CmdWhisper(_DefaultCmdWhisper):
    """
    Whisper privately to someone.

    Usage:
      whisper <target> = <message>
      whisper <target> <message>

    Whispering to an NPC who can speak (has an AI personality) routes
    the message to them as a private conversation — the NPC replies
    only to you, not the room.
    """
    key = "whisper"

    def func(self):
        caller = self.caller
        args = (self.args or "").strip()
        if not args:
            return super().func()

        target, message = _parse_target_and_message(caller, args)
        if not target or not message:
            return super().func()

        if target.attributes.get("ai_personality", default=None):
            from world import ai_npc
            from world.npc_gifts import process_gift_markers

            def _on_reply(reply):
                if not reply:
                    reply = "..."
                reply = process_gift_markers(reply, target, caller)
                if not reply:
                    reply = "..."
                caller.msg(
                    f'|c{target.key}|n whispers to you, "{reply}"'
                )
                _fire_npc_dialogue(caller, target, message, reply, channel="whisper")

            caller.msg(f"|gYou whisper to {target.key}, \"{message}\"|n")
            caller.msg(f"|x({target.key} leans in to listen...)|n")
            ai_npc.chat(target, caller, message, _on_reply)
            return

        # Not an AI NPC — hand off to default whisper behavior.
        return super().func()


class CmdSay(_DefaultCmdSay):
    """
    Speak aloud to everyone in the room.

    Usage:
      say <message>
      "<message>      (shortcut)

    Everyone in the room hears you. If your message names an AI NPC
    in the room, that NPC will respond — addressing them directly is
    the natural way to start a conversation with them.

    For a private one-on-one with an NPC, use:
      ask <npc> <question>      — direct question
      whisper <npc>=<message>   — private speech
    """
    key = "say"

    def func(self):
        # Run the default say first so the room hears the speech.
        super().func()
        # Then check whether any AI NPC in the room was addressed by
        # name. If so, route the message through the LLM to that NPC.
        message = (self.args or "").strip().lstrip(":'\"").strip()
        if not message:
            return
        location = self.caller.location
        if not location:
            return
        addressed = []
        msg_lower = message.lower()
        for obj in location.contents:
            if obj == self.caller:
                continue
            if not obj.attributes.get("ai_personality", default=None):
                continue
            # Match the NPC's key OR any of their aliases against
            # whole words in the message. "hegga" matches "Hegga,"
            # but not "Heggard" or "agghegg".
            candidates = [obj.key.lower()]
            try:
                candidates.extend(a.lower() for a in obj.aliases.all())
            except Exception:
                pass
            for cand in candidates:
                if not cand:
                    continue
                # Word-boundary check: the candidate appears in msg
                # surrounded by spaces, punctuation, or string edges.
                import re
                pattern = r"\b" + re.escape(cand) + r"\b"
                if re.search(pattern, msg_lower):
                    addressed.append(obj)
                    break
        if not addressed:
            return
        # Route the message to the first matched NPC (avoid spamming
        # multiple NPCs from a single say). Subsequent NPCs would need
        # their own ask / direct address.
        target = addressed[0]
        from world import ai_npc

        def _on_reply(reply):
            if not reply:
                reply = "..."
            location.msg_contents(
                f'|c{target.key}|n says, "{reply}"'
            )
            _fire_npc_dialogue(self.caller, target, message, reply, channel="say")

        location.msg_contents(
            f"|x({target.key} considers your words...)|n",
            from_obj=self.caller,
        )
        ai_npc.chat(target, self.caller, message, _on_reply)


class CmdFarewell(Command):
    """
    End a conversation. The NPC forgets what you discussed.

    Usage:
      farewell <npc>

    Useful if you want the NPC to start a fresh conversation next time,
    or if the history has become cluttered.
    """
    key = "farewell"
    aliases = ["bye"]
    locks = "cmd:all()"
    help_category = "Social"

    def func(self):
        caller = self.caller
        target_name = (self.args or "").strip()
        if not target_name:
            caller.msg("Say farewell to whom?")
            return
        target = caller.search(target_name, location=caller.location)
        if not target:
            return
        if not target.attributes.get("ai_personality", default=None):
            caller.msg(f"{target.key} has nothing to say anyway.")
            return
        from world import ai_npc
        ai_npc.reset_history(target, caller)
        if caller.location:
            caller.location.msg_contents(
                f"|g{caller.key}|n bids |c{target.key}|n farewell."
            )
